apiVersion: apps/v1
kind: Deployment
metadata:
    name: load-balancer
spec:
    replicas: 3
    selector:
        matchLabels:
            app: load-balancer
    template:
        metadata:
            labels:
                app: load-balancer
        spec:
            containers:
                - name: load-balancer
                  image: <dockerhub-username>/load-balancer
                  ports:
                      - containerPort: 8080
